### ISSUE TITLE
No fan data for ASUS TUF GAMING X570-PLUS (WI-FI) or NVIDIA NVIDIA GeForce RTX 3080

### ISSUE THREAD

**Issue by Gibby** [nickbabcock/OhmGraphite#247] opened 2021-10-16 15:17 UTC
I can see fan data in Libra Hardware Monitor and in Prometheus, however the Prometheus sample dashboard has blank info for fan data.

```
# HELP ohm_gpunvidia_revolutions_per_minute Metric reported by open hardware sensor
# TYPE ohm_gpunvidia_revolutions_per_minute gauge
ohm_gpunvidia_revolutions_per_minute{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 1",hw_instance="0"} 0
ohm_gpunvidia_revolutions_per_minute{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 2",hw_instance="0"} 1715

# HELP ohm_gpunvidia_control_percent Metric reported by open hardware sensor
# TYPE ohm_gpunvidia_control_percent gauge
ohm_gpunvidia_control_percent{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 1",hw_instance="0"} 70
ohm_gpunvidia_control_percent{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 2",hw_instance="0"} 70


# HELP ohm_superio_revolutions_per_minute Metric reported by open hardware sensor
# TYPE ohm_superio_revolutions_per_minute gauge
ohm_superio_revolutions_per_minute{hardware="Nuvoton NCT6798D",sensor="Fan #3",hw_instance="nct6798d"} 0
ohm_superio_revolutions_per_minute{hardware="Nuvoton NCT6798D",sensor="Fan #4",hw_instance="nct6798d"} 0
ohm_superio_revolutions_per_minute{hardware="Nuvoton NCT6798D",sensor="Fan #7",hw_instance="nct6798d"} 477.8760986328125
ohm_superio_revolutions_per_minute{hardware="Nuvoton NCT6798D",sensor="Fan #1",hw_instance="nct6798d"} 538.7070922851562
ohm_superio_revolutions_per_minute{hardware="Nuvoton NCT6798D",sensor="Fan #6",hw_instance="nct6798d"} 1904.0902099609375
ohm_superio_revolutions_per_minute{hardware="Nuvoton NCT6798D",sensor="Fan #2",hw_instance="nct6798d"} 481.9707336425781
ohm_superio_revolutions_per_minute{hardware="Nuvoton NCT6798D",sensor="Fan #5",hw_instance="nct6798d"} 2842.105224609375

# TYPE ohm_superio_control_percent gauge
ohm_superio_control_percent{hardware="Nuvoton NCT6798D",sensor="Fan Control #3",hw_instance="nct6798d"} 100
ohm_superio_control_percent{hardware="Nuvoton NCT6798D",sensor="Fan Control #7",hw_instance="nct6798d"} 100
ohm_superio_control_percent{hardware="Nuvoton NCT6798D",sensor="Fan Control #2",hw_instance="nct6798d"} 70.98039245605469
ohm_superio_control_percent{hardware="Nuvoton NCT6798D",sensor="Fan Control #1",hw_instance="nct6798d"} 31.372549057006836
ohm_superio_control_percent{hardware="Nuvoton NCT6798D",sensor="Fan Control #4",hw_instance="nct6798d"} 100
ohm_superio_control_percent{hardware="Nuvoton NCT6798D",sensor="Fan Control #5",hw_instance="nct6798d"} 49.80392074584961
ohm_superio_control_percent{hardware="Nuvoton NCT6798D",sensor="Fan Control #6",hw_instance="nct6798d"} 81.5686264038086
```

![image](https://user-images.githubusercontent.com/503761/137592674-bfd75daf-11a7-4d20-bfc1-a5bc12a86a3d.png)
![image](https://user-images.githubusercontent.com/503761/137592691-67a0a4fa-8b05-487e-b389-a0767ed2ae06.png)
![image](https://user-images.githubusercontent.com/503761/137592699-bdd9b897-9a47-428b-83c0-4780aaf35ed5.png)

I tried messing around the query but no luck so far.

**Comment by Gibby** [comment] 2021-10-18 12:38
I updated Libre Hardware Monitor, and I am seeing both fan % and fan rpm for both my motherboard and GPU in Libre Hardware Monitor and also I see values for percent and RPM in Prometheus. 

![image](https://user-images.githubusercontent.com/503761/137731657-a72a84d1-5ca7-4725-b6bd-75394e5cb560.png)
![image](https://user-images.githubusercontent.com/503761/137731704-a21c65e5-cff2-429c-8eb1-807a1e5bf280.png)

```
ohm_gpunvidia_control_percent{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 2",hw_instance="0"} 70
ohm_gpunvidia_control_percent{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 1",hw_instance="0"} 70
ohm_gpunvidia_revolutions_per_minute{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 2",hw_instance="0"} 1716
ohm_gpunvidia_revolutions_per_minute{hardware="NVIDIA GeForce RTX 3080",sensor="GPU Fan 1",hw_instance="0"} 1711
```

**Comment by nickbabcock** [comment] 2021-10-20 02:08
Hmm, what could it be? Since it looks like the data is being transmitted to prometheus, it appears to be purely a display issue. Are you running the latest Grafana (v8.2.1)? I think there were some important bug fixes lately

**Comment by nickbabcock** [comment] 2021-10-30 00:28
Let me know if there's an update, else I'll close this in the foreseeable future.

**Comment by badrpc** [comment] 2021-11-12 10:49
In JSON model there's a transformation block in both fan panels:

```
      "transformations": [
        {
          "id": "configFromData",
          "options": {
            "applyTo": {
              "id": "byFrameRefID",
              "options": "A"
            },
            "configRefId": "C",
            "mappings": [
              {
                "fieldName": "High RPM",
                "handlerKey": "threshold1"
              }
            ]
          }
        }
      ],
```

removing the transformation recovers the graphs. I don't know much about transformations and didn't have time to look more into this yet. I just left it as

```
      "transformations": [
      ],
```

it's possible this has left something else broken but at least I can see the graphs.

**Comment by nickbabcock** [comment] 2021-11-12 12:38
@badrpc, are you running the latest grafana v8.1.0+? The config from data transformation is a relatively new feature which can consolidate two graphs into one.

**Comment by badrpc** [comment] 2021-11-12 15:41
No, I'm still on 8.0.5. Will check the recent version if I can get it via FreeBSD packages.

To make it clear - I'm not complaining. I ended up on this bug because for some weird reason exporter stopped exporting fan RPM data (and both Libre Hardware Monitor and Fan Control were still seeing them) and my motherboard happened to be Asus TUF Gaming X570-PLUS. I then figured out that current issue was for a different problem and somehow my issue got resolved (still have no idea what started it and how it got fixed which is annoying). However I was curious to check the dashboard and try to find what was the problem here.

**Comment by badrpc** [comment] 2021-11-12 16:03
I can confirm graphs are working on 8.1.7.

**Comment by nickbabcock** [comment] 2021-11-13 14:24
> I can confirm graphs are working on 8.1.7.

Great to hear. It's kinda hard to design a compatible and good-looking dashboard around all the different combinations of hardware and grafana versions.

I'll document that the prometheus starting dashboard requires grafana v8.1+

**Closed** 2021-11-23 22:43 UTC
