### ISSUE TITLE
grafana 7.4.0+ requires changes in template variables (prometheus)

### ISSUE THREAD

**Issue by swiffer** [nickbabcock/OhmGraphite#188] opened 2021-01-09 09:51 UTC
grafana 7.4.0+ requires using `?<value>` in regex for variables:

e.g.

```regex
/ohm_(?<value>\w+)_volts.*/
```

![grafik](https://user-images.githubusercontent.com/2990373/104088634-954f2300-5268-11eb-9be3-5f11421d85a2.png)

without:

![grafik](https://user-images.githubusercontent.com/2990373/104088655-c29bd100-5268-11eb-87d2-9cffd19a6ee2.png)

**Comment by nickbabcock** [comment] 2021-01-09 14:00
Thank you for the report. Is there any context for this change (like a PR or changelog entry), so I can familiarize myself as it seems odd to introduce (what seems like) a breaking change.

Do you know of a way that we can structure dashboard variables so they don't break on 7.4.0+?

**Comment by swiffer** [comment] 2021-01-09 14:13
https://grafana.com/docs/grafana/latest/variables/filter-variables-with-regex/#filter-and-modify-using-named-text-and-value-capture-groups

But I guess it's more a regression in grafana. Reading the paragraphs above the way you are using it currently should still work just fine, right?

**Comment by nickbabcock** [comment] 2021-01-20 23:24
Saw that the first 7.4.0 beta has been released. I'm curious if this this issue has been fixed. Have you tested this, @swiffer ?

**Comment by swiffer** [comment] 2021-01-25 13:50
yes, it still happens in 7.4.0-beta1 (reimported the dashboard from your repo)

![grafik](https://user-images.githubusercontent.com/2990373/105714411-98ab0580-5f1c-11eb-97ea-342f8706f695.png)

**Comment by nickbabcock** [comment] 2021-01-26 03:01
Reported upstream: https://github.com/grafana/grafana/issues/30617

**Comment by nickbabcock** [comment] 2021-01-27 00:00
Confirmed grafana issue and looks like it will be fixed before the release, so I'm closing the issue.

**Closed by nickbabcock** 2021-01-27 00:00 UTC
